---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - tag

clone:
  depth: 1

steps:
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: remote_host
      username:
        from_secret: remote_username
      target: /Users/rinku/Docker/volumes/api/chef-gpt-api
      source: .
